---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: src/gallery_posts
  label: Gallery
  create: documents
  match: "*.md"
  templates:
  - photo
- type: directory
  path: src/prestations_posts
  label: Prestations
  create: documents
  match: "*.md"
  templates:
  - prestation
upload_dir: src/img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_docker_image: node:12
  install_dependencies_command: npm install
  instant_preview_command: npx eleventy --serve
  mount_path: "/srv"
  working_dir: "/srv/src"
  preview_output_directory: "src/dist"
  preview_env:
    - ENV=staging
